# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  name: Default
  vmImage: ubuntu-latest

parameters:
  - name: name
    displayName: Enter name
    type: string
  - name: file
    displayName: Enter file name
    type: string
stages:
  - stage: tfinstallvalidate
    
    jobs:
      - job: validate
        continueOnError: false
        steps: 
         - task: TerraformInstaller@1
           displayName: tfinstall
           inputs:
             terraformVersion: 'latest'
         - script: |
             echo Add other tasks to build, test, and deploy your project.
             echo ${{parameters.name}} "succesfully triggered this build from a REST API call"
             echo "name=${{parameters.name}}" >> ${{parameters.file}}
             ls -lart
             cat ${{parameters.file}}
             git add -A
             git commit -m "commit message"
             git push
           displayName: 'Run a multi-line script'
