# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest
  name: Default

parameters:
  - name: name
    displayName: Enter name
    type: string
  - name: redirect_uris
    displayName: Enter redirect_uris name
    type: string
  - name: CI
    displayName: Enter CI name
    type: string
  - name: identifier_uris
    displayName: Enter identifier name
    type: string
  - name: application_name
    displayName: Enter appName name
    type: string
  - name: aad_group
    displayName: Enter aad_group name
    type: string
stages:
  - stage: tfinstallvalidate
    jobs:
      - job: validate
        continueOnError: false
        steps: 
        - checkout: self
          persistCredentials: true
        - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
          displayName: tfinstall
          inputs:
            terraformVersion: 'latest'
        - task: TerraformCLI@0
          inputs:
            command: 'workspace'
            workspaceSubCommand: 'new'
            workspaceName: ${{parameters.CI}}
            allowTelemetryCollection: false
            skipExistingWorkspace: true
        - script: |
             pwd
             ls -lart
        - script: |
             echo Add other tasks to build, test, and deploy your project.
             echo ${{parameters.name}}" succesfully triggered this build from a REST API call"
             echo "application_name=\"${{parameters.application_name}}\"" >> ${{parameters.CI}}
             echo "identifier_uris=[\"${{parameters.identifier_uris}}\"]" >> ${{parameters.CI}}
             echo "aad_group=\"${{parameters.aad_group}}\"" >> ${{parameters.CI}}
             echo "redirect_uris=[\"${{parameters.redirect_uris}}\"]" >> ${{parameters.CI}}
             ls -lart
             cat ${{parameters.CI}}
             git config user.email "vabby@vyconsultants.com.au"
             git config user.name "Azure DevOps Pipeline"
             ls -lart
             cat ${{parameters.CI}}
             git add -A
             git commit -m "deployment $(Build.BuildNumber)"
             git push --set-upstream origin HEAD:main
          displayName: 'Run a multi-line script'
        - script: |
             export ARM_CLIENT_ID="f31bed50-c132-4dc1-bafb-c76758297304"
             export ARM_CLIENT_SECRET="v3e8Q~0bMzbF76eHjmhJmlpXu_Z~ODmPRm.2Mb6y"
             export ARM_SUBSCRIPTION_ID="5c5cbbf6-f3fc-47a2-8f66-5b9a2d4f01ae"
             export ARM_TENANT_ID="9595ba37-989b-44d1-8b01-e08c12a976a7"
          displayName: 'Set Env'
        - script: |
             terraform init
          displayName: 'Init'
        - script: |
             terraform validate
          displayName: 'Validate'
        - script: |
             echo $ARM_CLIENT_ID
             echo $ARM_SUBSCRIPTION_ID
             echo $ARM_TENANT_ID
             echo $ARM_CLIENT_SECRET
             terraform plan
          displayName: 'Plan'